### ISSUE TITLE
关于图片、标题对齐的建议

### ISSUE THREAD

**Issue by hi-nikola** [aircloud/hexo-theme-aircloud#101]
1.文章中插入图片默认是左对齐的  能否设置多种选择？比如居中。
2.电脑版浏览博客 副标题和文章标题是错位的，并不是同时居中的
![image](https://user-images.githubusercontent.com/52887883/167077281-8e18d2de-81ec-4046-9e3e-2566969bc4e7.png)

**Comment by aircloud** [comment]
第一个应该近期可以支持一下。

第二个的话，应该是设计如此。。 主站副标题是全局居中，文章标题是右侧居中
