### ISSUE TITLE
怎么设置头像？

### ISSUE THREAD

**Issue by xiaosmile707** [aircloud/hexo-theme-aircloud#12]
在_config.yml设置avatar好像也不行

**Comment by aircloud** [comment]
如果你的 _config.yml 有这一行的话：

sidebar-avatar: img/avatar.jpg 

在你的博客目录新增或者替换 source/img/avatar.jpg 然后刷新即可。

可以参考 https://github.com/aircloud/hexo-aircloud-blog 中的头像配置

**Comment by aircloud** [comment]
如果没有更多问题，该 issue 暂时关闭，还有问题请重新开 issue
