### ISSUE TITLE
导航栏"home"按钮链接写死导致部署后网站不一定正确导航

### ISSUE THREAD

**Issue by tankgit** [aircloud/hexo-theme-aircloud#13]
[nav.ejs  - line 14](https://github.com/aircloud/hexo-theme-aircloud/blob/master/layout/_partial/nav.ejs)

home标签的链接地址写死成了'/'，如果用hexo生成静态网站后，部署到服务器的某个子目录，即使修改_config.yml下的root变量，也会导致点击home标签导航到域名根目录。

Solution: 修改href的值
```html
href="<%= url_for(config.home_dir)  %>"
```

**Comment by aircloud** [comment]
谢谢，你这个提议我会立刻采纳
