### ISSUE TITLE
博客中图片的使用

### ISSUE THREAD

**Issue by xingliuhua** [aircloud/hexo-theme-aircloud#16]
你好，请问博客中应该怎么使用图片？图片放哪里？

**Comment by aircloud** [comment]
图片的使用方式即按照 hexo 的使用方式即可，当你 `hexo new` 一个文件夹后，会生成对应同名文件夹，图片等资源放置在其中并且按照 markdown 的图片语法相对路径引入即可。 

也可以参考官方文档：https://hexo.io/zh-cn/docs/asset-folders
