### ISSUE TITLE
评论功能登陆github失效了

### ISSUE THREAD

**Issue by liuyangzuo** [aircloud/hexo-theme-aircloud#17]

**Comment by aircloud** [comment]
你这边是点击登陆出现 404 嚒？
如果是的话的确在某些环境会这样，这个评论部分用的第三方的... 我之后会定位下问题

**Comment by liuyangzuo** [comment]
![4621536286502_ pic_hd](https://user-images.githubusercontent.com/8985760/45194745-ee68af80-b286-11e8-9422-bd3fc7a514de.jpg)
![4611536286479_ pic_hd](https://user-images.githubusercontent.com/8985760/45194746-f0cb0980-b286-11e8-976c-cd60d4cbba5a.jpg)

**Comment by aircloud** [comment]
应该是这个第三方插件有点问题...emmm...

这个我之后考虑下是魔改一下还是换个评论系统吧，大家有好的方案也欢迎指出

p.s. 目前有小伙伴指出可以使用来必力，这个我考虑下，作为一个备选方案

**Comment by liuyangzuo** [comment]
disqus可以用的吧

**Comment by aircloud** [comment]
disqus 已经集成进去了
