### ISSUE TITLE
favicon.ico还是没有显示

### ISSUE THREAD

**Issue by aretlas** [aircloud/hexo-theme-aircloud#18]
favicon.ico是放在根目录的source/img下 不知为何还是没有显示……

**Comment by aircloud** [comment]
一般来说，你直接放在 source/img 下就可以了，但前提是你没有对相关配置做过改动。

这里我建议你可以先看下[DEMO](https://github.com/aircloud/hexo-aircloud-blog) 尝试一下 DEMO 中的 favicon.ico 是否可以成功显示并且被替换。

实际上，在 demo 项目中 favicon 的地址在 `/hexo-aircloud-blog/themes/aircloud/layout/_partial/head.ejs` 中有写到：

```
    <link rel="shortcut icon" href="<%= config.root %>img/favicon.ico">
```
