### ISSUE TITLE
gitment第一次加载不动

### ISSUE THREAD

**Issue by Xenos3811** [aircloud/hexo-theme-aircloud#19]
这是控制台信息
火狐转成中文了:![image](https://user-images.githubusercontent.com/34369858/45832586-e43dbb00-bd34-11e8-9f55-71883e015c56.png)

使用谷歌:
![image](https://user-images.githubusercontent.com/34369858/45832629-03d4e380-bd35-11e8-91e5-981d10077615.png)

然后页面加载不动:
![image](https://user-images.githubusercontent.com/34369858/45832636-1222ff80-bd35-11e8-861b-b80de044b681.png)

我想问一下博主,该怎么解决啊.,

**Comment by aircloud** [comment]
首先感谢支持，gitment 这个插件本身貌似现在有些问题，我十月一国庆结束前会把这个项目进行一次大的更新，包括提供其他的评论系统的接入。

最近这两天还在赶工作进度...

**Comment by aircloud** [comment]
Disqus 的接入前段时间完成并且更新了

如果之后你还有问题。。可以在开这个issue或者新提问
