### ISSUE TITLE
能支持Disqus就好了

### ISSUE THREAD

**Issue by miranquil** [aircloud/hexo-theme-aircloud#20]
Gitment还是不太喜欢它那个方式。。

**Comment by aircloud** [comment]
嗯嗯，正好我也打算支持下 Disqus...
我国庆结束前会更新一个大的版本，顺带解决其他 issue 中提到的一些问题。

p.s. 国庆前这几天还在上班赶进度...

**Comment by miranquil** [comment]
那加油哈，我正在准备迁移到这个主题

**Comment by aircloud** [comment]
disqus 已经支持并更新文档
