### ISSUE TITLE
集成gitbook

### ISSUE THREAD

**Issue by joeaaron** [aircloud/hexo-theme-aircloud#21]
大神你好，我想把gitbook集成到这个主题下，有没有什么范例可以提供参考啊，比如主页、标签、存档、关于、搜索下再多一个

**Comment by aircloud** [comment]
额，你这里的“集成” 指的是把 gitbook 生成的 html 文件放在 hexo 下面嚒，这样的话类似[这篇文章](https://mdengli.com/hexo-gitbook/) 的做法就可以了，如果你想要更高级的功能或者更深度的适配，可以在这个 issue 下评论，正好我国庆期间会对这个项目进行一个版本更新，可以考虑把你提到的功能做进去。

**Comment by joeaaron** [comment]
类似于书架功能，有一个板块里存放的就是自己写的书。

**Comment by aircloud** [comment]
嗯嗯我大概了解了... 主要是 gitbook 我也没有用的太多，自认为对大多数人来说可能也不是一个高频的需求，所以短期内应该不考虑支持这个功能。

当然，后续可能会考虑，也欢迎你提 PR
