### ISSUE TITLE
如何修改主页的个人头像

### ISSUE THREAD

**Issue by LinuxLeeSin** [aircloud/hexo-theme-aircloud#25]
尊敬的作者您好，初学者对HTML不太懂，跟着那个readme添加了自己的favicon.ico，但是头像没有变化；
另外那个标签和关于页面，添加了index.md之后，写入
---
    layout: "tags"
    title: "Tags"
---

---
    layout: "about"
    title: "About"
    date: 2016-04-21 04:48:33
    comments: true
---
但是访问是空白页

还需要对哪里进行设置吗，谢谢！

**Comment by LinuxLeeSin** [comment]
大大你好，头像问题算是解决了一部分吧，直接把你的_config.yml复制过来修改了一下，其他标签可以正常工作了，但是访问主页的时候左边栏全是英文，个人头像依旧不会显示；另外如何添加在标签那一栏添加标签，方便指导一下吗，感激不尽！

**Comment by LinuxLeeSin** [comment]
www.linuxleesinloveyy.cn   好像刷新慢了点，原来修改是有效果的，那就剩下一个标签的问题了，不知道在.md里文件用什么语法做出那种标签效果啊

**Comment by aircloud** [comment]
头像：

如果你的 _config.yml 有这一行的话：

sidebar-avatar: img/avatar.jpg 

在你的博客目录新增或者替换 source/img/avatar.jpg 然后刷新即可。

可以参考 https://github.com/aircloud/hexo-aircloud-blog 中的头像配置

标签：

我看你的标签好像是有效果了，不知道现在还有问题吗

**Comment by LinuxLeeSin** [comment]
> 头像：
> 
> 如果你的 _config.yml 有这一行的话：
> 
> sidebar-avatar: img/avatar.jpg
> 
> 在你的博客目录新增或者替换 source/img/avatar.jpg 然后刷新即可。
> 
> 可以参考 https://github.com/aircloud/hexo-aircloud-blog 中的头像配置
> 
> 标签：
> 
> 我看你的标签好像是有效果了，不知道现在还有问题吗

 `看你的配置文件自己摸索了一会，基本样式和操作没问题了，其他的接下来我自己慢慢捣鼓，慢慢学习了，感谢这个美丽的主题`

**Comment by btb16137** [comment]
@aircloud  我在_config.yml 里面设置了
sidebar-avatar: img/avatar.jpg 
post_asset_folder: true 
图片放在了
根目录\source\img\avatar.jpg
但是就是不显示，好奇怪，麻烦帮忙解答一下
