### ISSUE TITLE
如何增加page菜单？

### ISSUE THREAD

**Issue by wongoo** [aircloud/hexo-theme-aircloud#26]
如题

**Comment by aircloud** [comment]
支持的功能都已经在 readme 中写出了噢，根据你的描述可能这个功能还不支持，不过我并没有完全 get 你的意思，如果需要的话你可以详细讲一下～

**Comment by wongoo** [comment]
左侧菜单目前只有` HOME、TAGS、ARCHIVES、ABOUT、SEARCH `， 怎么讲 `hexo new page` 创建的页面加到菜单中？

**Comment by aircloud** [comment]
这个功能暂时不支持噢

**Comment by a1t3r570** [comment]
> 这个功能暂时不支持噢

您好，不知道aircloud支持categories么？就是左侧菜单目前只有tags,感觉需要一个分类菜单，nexT主题是有的.就算不能hexo new page自定义页面的话，可不可以优先添加这个功能..很喜欢您的主题
