### ISSUE TITLE
关于自己和标签该怎么写，写在index中不显示

### ISSUE THREAD

**Issue by charmsongo** [aircloud/hexo-theme-aircloud#28]
关于自己和标签该怎么写，写在index中不显示

**Comment by aircloud** [comment]
https://github.com/aircloud/hexo-theme-aircloud#%E6%A0%87%E7%AD%BE%E9%A1%B5%E9%9D%A2--%E5%85%B3%E4%BA%8E%E9%A1%B5%E9%9D%A2
