### ISSUE TITLE
修改_config.yml后无改变

### ISSUE THREAD

**Issue by RoiexLee** [aircloud/hexo-theme-aircloud#3]

**Comment by aircloud** [comment]
能否提供一下详细信息，比如哪个config？

提示：修改_config.yml之后需要重新 hexo s 一下

**Comment by RoiexLee** [comment]
已经解决了，一开始修改的是主题配置文件所以没有改变，感谢作者大大的关心😆

2018年4月23日(月) 20:03 Xiaotao <notifications@github.com>:

**Comment by aircloud** [comment]
谢谢支持～
