### ISSUE TITLE
about 和 tags 文件夹均已经建立，并且写入index.md，测试时这两个页面都是空的，请问是哪里的问题？

### ISSUE THREAD

**Issue by pythonfirst** [aircloud/hexo-theme-aircloud#31]

**Comment by aircloud** [comment]
需要建立在 source 文件夹下噢，这个可以确认下

**Comment by aircloud** [comment]
另外你可以看看和[DEMO](https://github.com/aircloud/hexo-aircloud-blog)的配置有什么不一样的地方

**Comment by pythonfirst** [comment]
您好找到原因并解决了。原因是我手动在编辑器中新建about 、tags文件夹和相应的index.md文件，在配置文件完全相同的情况下，tags和about 页面都显示为空。解决方案是在终端使用 hexo new page tags 创建新页面，这样可以正常显示，about 页面同tags。
建议您在 Readme 文档中的tags & about 部分把这条命令补充上，这样以后新手来了就不会出现此问题了。
谢谢您的回复！

**Comment by aircloud** [comment]
好的，我会采纳你的建议，谢谢～
