### ISSUE TITLE
* 缩进太大，如何更改

### ISSUE THREAD

**Issue by machinelife1989** [aircloud/hexo-theme-aircloud#32]
在markdown中使用*标记时，呈现时缩进太大。

是否可取消缩进。或者配置缩进？

**Comment by aircloud** [comment]
目前，列表的缩进是一个固定的值，如果想要修改，最快速的办法就是修改源文件：

```
themes/aircloud/source/_less/post.css
```
（如果可以实时编译less，也可以修改对应的less文件）

**Comment by aircloud** [comment]
关于项目中是否可配置，这个会再考虑评估目前样式的合理性，谢谢你的支持～
