### ISSUE TITLE
文章中总出现一竖条类似于可以上下拖动的那种

### ISSUE THREAD

**Issue by orange723** [aircloud/hexo-theme-aircloud#35]
用火狐查看基本是没有，chrome有些文章有有些出来一会就没有了，存在于文章左侧就和浏览器右边可以上下拖动的滚动条，但文章中是不可拖动的

**Comment by aircloud** [comment]
这个问题我这边也发现了哈，本周查下原因修复掉（工作日有点忙，估计周末才能修复了。。）。

你也可以尝试自己修改一下，应该是目录的问题～

感谢你的支持

**Comment by JianYu97** [comment]
😂  感谢回复，等待你的修复

Xiaotao <notifications@github.com> 于2018年12月3日周一 下午6:17写道：

**Comment by aircloud** [comment]
这个问题两天前已经修复了，可以重新更新代码。

由于是场景性问题，如果还出现，可以再开启 issue。

**Comment by ioxera** [comment]
@aircloud 此问题又出现于firefox中，在chrome不显示滚动条，但是和firefox一样无法滚动到页面底部。查看页面元素发现如下
![Screenshot_20190329_210425](https://user-images.githubusercontent.com/22150551/55235053-82bc5300-5267-11e9-810b-cb2e22bd3ad1.png)
![Screenshot_20190329_210453](https://user-images.githubusercontent.com/22150551/55235227-024a2200-5268-11e9-92a9-97c0447f4cca.png)
元素toc的height属性导致此问题，禁用此属性则滚动条长度限制消失，但在firefox中滚动条图像依然存在，禁用overflow-y属性，则滚动条消失，页面正常显示。
查看主题代码发现是layout/_partial/nav.ejs第51行代码引起，注释此代码则目录和滚动条同时消失。此代码调用./toc生成目录，注释layout/_partial/toc.ejs第2行对toc函数的调用，则目录消失，滚动条存在。

**遂迷，不复得路**
