### ISSUE TITLE
markdown的code语法在手机端浏览器的展示兼容问题

### ISSUE THREAD

**Issue by machinelife1989** [aircloud/hexo-theme-aircloud#36]
当时用```进行标记时。pc端展示正常。
移动端展示时，有的字体正常，有的字体偏大。

是不是CSS的动态设置的问题

**Comment by machinelife1989** [comment]
移动端，对于```标记内容，有的字体正常，有的字体是稍大一点。有的字体是大很多。

**Comment by aircloud** [comment]
这个我看看能不能复现，你也可以提供截图参考～

**Comment by machinelife1989** [comment]
![粘贴图片.png](https://upload-images.jianshu.io/upload_images/1401040-fbfc71d43c0ebf5c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by machinelife1989** [comment]
如上图所示，上面和下面在```中标记的文字大小不一。

**Comment by aircloud** [comment]
额 谢谢你提供的截图，我具体看下

**Comment by aircloud** [comment]
刚试了一下，按照一般 markdown 的写法，不同 ```中标记的文字 并没有出现上述问题，感觉这个问题和 markdown  的解析有关，目前还不能确定具体问题，所以如果你能够将出问题的 markdown 文件发一个给我以及告诉我出问题的手机和浏览器型号，可能会有助于我解决问题。。。

非常抱歉哈，同时谢谢你支持这个项目。

**Comment by machinelife1989** [comment]
辛苦！

在QQ浏览器上没问题。在苹果的safari浏览器/uc浏览器上有问题。
可以在手机上访问这个页面，复现这个问题：

https://www.xupeng.tech/2018/07/20/%E8%AE%BA%E8%A7%82%E4%B9%A6/

**Comment by aircloud** [comment]
你这个问题的确是一个好问题，我也是找了一会才找到。

首先说解决方案，你可以手动加一个全局样式：

```
 body{
    -webkit-text-size-adjust: none;
 }
```
或者仅仅给 pre 标签加上：
```
 pre {
    -webkit-text-size-adjust: none;
 }
```
这个问题的原因是触发了 Safari 的渲染问题，会导致其忽视我在 pre 标签设置的字体大小，更详细也可以参考[这里](https://stackoverflow.com/questions/3226001/some-font-sizes-rendered-larger-on-safari-iphone)


我这边在 Safari 浏览器回归正常了。

**Comment by machinelife1989** [comment]
嗯嗯 👍
