### ISSUE TITLE
hexo g  报错，cant read property ‘path’ of undefined

### ISSUE THREAD

**Issue by javaDuQing** [aircloud/hexo-theme-aircloud#4]
cant read property ‘path’ of undefined
hexo-theme-aircould/layout/layout.ejs
window.hexo_search_path = "<%- config.search.path %>"

感觉博主，希望能在空闲的时候能够解答。谢谢

**Comment by aircloud** [comment]
首先谢谢你的支持，提出的问题的确存在，目前已经修复。

建议：

如果需要添加搜索，参考[这里](https://github.com/aircloud/hexo-theme-aircloud#%E6%90%9C%E7%B4%A2%E5%8A%9F%E8%83%BD)
同时建议参考[这里的DEMO](https://github.com/aircloud/hexo-aircloud-blog)查看配置

**Comment by aircloud** [comment]
暂时没有新问题，先关闭该issue
