### ISSUE TITLE
关于取消搜索功能

### ISSUE THREAD

**Issue by LuhangRui** [aircloud/hexo-theme-aircloud#49]
0.主题里边的_config.yml是空的？

1.貌似我在主题中的_config.yml里设置search: false，语言会变成中文？没有在代码中找到这部分逻辑

![image](https://user-images.githubusercontent.com/30895030/52777887-c83e0b80-307f-11e9-8eba-afce338fb6f9.png)

看这部分逻辑，应该走的是主配置文件里的search 可是设置了，为什么这个搜索的li标签还是会显示呢？

请楼主指点一下

**Comment by aircloud** [comment]
因为我们所采用的插件会自动填充一些内容，所以需要删除对应的插件：

```
npm uninstall hexo-generator-search
```

中英文切换应该和搜索是否显示没关系，这个可以再确定下

**Comment by LuhangRui** [comment]
ok 感谢回复
