### ISSUE TITLE
about页面comments设置false 评论仍然显示

### ISSUE THREAD

**Issue by tea9** [aircloud/hexo-theme-aircloud#54]
---
layout: "about"
title: "About"
date: 2019-03-15 14:28:10
comments: false
---

**Comment by tea9** [comment]
![image](https://user-images.githubusercontent.com/39117901/54732906-5e120c80-4bd1-11e9-8821-be2ee5b88344.png)



![image](https://user-images.githubusercontent.com/39117901/54732854-17bcad80-4bd1-11e9-8daa-67bdd46bc64f.png)

**Comment by aircloud** [comment]
这个主题的确本来就不支持这种设置..

考虑之后更新上，也欢迎提 PR

**Comment by tankgit** [comment]
我跟你正好相反，我about页面设置成true也出不来。

我发现是Disqus的评论会出现这个问题，在主题的layout/about.ejs文件里`lv-container`元素上方加一句
```html
<div id="disqus_thread"></div>
```
就可以显示了，不过该主题目前仍然没有接入由`comments: true/false`字段控制评论开关的功能。

---

你可以发现，这个主题直接将gitment, disqus和livere三种评论平铺地放在layout底端，然而并没有使用相关变量控制其开关。如果你不想要，你可以简单地把about的layout文件中相应的`<div>`元素删掉，就可以关掉这个评论了。
