### ISSUE TITLE
使用4个空格的代码文字是白色的

### ISSUE THREAD

**Issue by tea9** [aircloud/hexo-theme-aircloud#57]
![image](https://user-images.githubusercontent.com/39117901/54658072-bdefb100-4b06-11e9-8211-21743870af37.png)
如图
![image](https://user-images.githubusercontent.com/39117901/54658112-e2e42400-4b06-11e9-98e7-6f0461794b4a.png)
把color:white;去掉就可以了

**Comment by aircloud** [comment]
已经看到MR 会尽快处理

**Comment by aircloud** [comment]
已经合并
