### ISSUE TITLE
友链多了会这样

### ISSUE THREAD

**Issue by tea9** [aircloud/hexo-theme-aircloud#59]
![image](https://user-images.githubusercontent.com/39117901/54685340-92de7f00-4b51-11e9-9103-0bd09c4b7e8e.png)

**Comment by aircloud** [comment]
是不是居中会好一些

**Comment by tea9** [comment]
我觉得是 可以向手机端 会两边有个边距 可能更好一些
![image](https://user-images.githubusercontent.com/39117901/54893994-78125e80-4ef3-11e9-8019-b510d9beb119.png)

**Comment by aircloud** [comment]
已经更新
