### ISSUE TITLE
目录多了样式会错乱

### ISSUE THREAD

**Issue by tea9** [aircloud/hexo-theme-aircloud#60]
![image](https://user-images.githubusercontent.com/39117901/54804043-03e67980-4cad-11e9-9263-db985efc651e.png)

![image](https://user-images.githubusercontent.com/39117901/54804057-16f94980-4cad-11e9-8e80-ad2df3525b17.png)

**Comment by aircloud** [comment]
这个问题延期解决下

**Comment by aircloud** [comment]
最新代码应该改善了
