### ISSUE TITLE
> md 引用标签文本显示错误

### ISSUE THREAD

**Issue by jzwyz** [aircloud/hexo-theme-aircloud#62]
本地文件
![image](https://user-images.githubusercontent.com/32916897/56787302-ace53e80-682e-11e9-9f42-2bfe9deb60ce.png)

gitlab 上显示
![image](https://user-images.githubusercontent.com/32916897/56787293-a2c34000-682e-11e9-8b46-b7c7586a912b.png)

最终在我的网站上面显示
![image](https://user-images.githubusercontent.com/32916897/56787337-c4bcc280-682e-11e9-82fd-6ef0366dd5c8.png)

我测试了, chrome、safari、小米手机浏览器...... 都是这样.
这个是什么问题?

**Comment by aircloud** [comment]
样式解析本来就是这样子的噢 （markdown 解析后的样式这里是自定义的），这个不是问题
