### ISSUE TITLE
文章内容比较短的时候，页面拉不到最下面，会上下闪动。这个问题已经很久了。

### ISSUE THREAD

**Issue by etan96** [aircloud/hexo-theme-aircloud#66]

**Comment by sisiyuyuzaiyiqi** [comment]
我把source\js\index.js里面这样改了一下：
function reHeightToc() {
  if (toc) {
    // resize toc height
    if (toc.children[0].childElementCount < 20) {
      toc.style.height = '600px';
      return;
    }
    toc.style.height = document.documentElement.clientHeight - 10 + 'px';
    toc.style.overflowY = 'scroll';
  }
}
这么改挺粗暴的。
原因感觉就是toc的height出的问题，文章太短的时候就抽搐了。
