### ISSUE TITLE
Maybe it will be better without 'text-indent' in '.post-content'

### ISSUE THREAD

**Issue by JackieAnxis** [aircloud/hexo-theme-aircloud#69]
Original:
![image](https://user-images.githubusercontent.com/19246028/60392580-94e4b080-9b38-11e9-8ad4-f6c2a85df9c0.png)

After remove 'text-index: 2em' in '.post-content':
![image](https://user-images.githubusercontent.com/19246028/60392579-931aed00-9b38-11e9-9282-ddb1fe7bdac9.png)

Just a personal suggestion.

**Comment by aircloud** [comment]
https://github.com/aircloud/hexo-theme-aircloud#%E9%A6%96%E8%A1%8C%E7%BC%A9%E8%BF%9B

首行缩进可以关闭
