### ISSUE TITLE
请问下面社交账号的icon怎么加的，搜索的好久没找到

### ISSUE THREAD

**Issue by tea9** [aircloud/hexo-theme-aircloud#73]
icon要怎么加，可以告诉我下吗…………^ _ ^
![image](https://user-images.githubusercontent.com/39117901/63146962-4bd8b500-c02f-11e9-890d-5113d93673e9.png)
![image](https://user-images.githubusercontent.com/39117901/63146969-53985980-c02f-11e9-87ac-835a08d9a073.png)
就是这个

**Comment by Sij-modpe** [comment]
这个应该是无法自定义的，你再去读一下readme.md

**Comment by tea9** [comment]
我是想改主题的代码 应该可以加的吧  我想加个简书的图标

**Comment by Sij-modpe** [comment]
> 我是想改主题的代码 应该可以加的吧 我想加个简书的图标

邮箱给我，或者验收一下邮箱（我把解决方案作为附件发给了notifications@github.com

**Comment by Sij-modpe** [comment]
我借楼请问一下作者，您使用的是阿里巴巴的矢量图标，于是我就在css里找这些<i>class属性所标示出的类名iconfont，但是很遗憾没有找到。请问能否说明一下这个iconfont究竟写在哪个css文件里?

**Comment by tea9** [comment]
tea90@qq.com 我也没找的图标库。。。

**Comment by aircloud** [comment]
> 我借楼请问一下作者，您使用的是阿里巴巴的矢量图标，于是我就在css里找这些class属性所标示出的类名iconfont，但是很遗憾没有找到。请问能否说明一下这个iconfont究竟写在哪个css文件里?

这个实际上是我自己组合的一套，入口文件放在了 `/layout/_partial/head.ejs`
