### ISSUE TITLE
如果你不喜欢列表的点 想换成- / If u don't like the circles, but want dashes, of list items

### ISSUE THREAD

**Issue by kuesugi** [aircloud/hexo-theme-aircloud#76]
平时比较喜欢写列表 但是感觉 • 太多比较不好看.

可以替换aircloud/source/css/aircloud.css 的 669行 (如果你没有更改过的行数)
或者直接搜索 `•`, 把它替换成 `-` .即可.

Just replace `•` with `-` in aircloud/source/css/aircloud.css line 669 (if u haven't changed the lines). Or just search `•` in the file and replace it.

**Comment by aircloud** [comment]
这个可以由使用者 强制覆盖一下
