### ISSUE TITLE
无法构建？

### ISSUE THREAD

**Issue by LLXBH** [aircloud/hexo-theme-aircloud#85]
下载并放入文件夹，更换主题，hexo g 就会出错
![image](https://user-images.githubusercontent.com/34165598/72202694-855a0300-349d-11ea-96ef-e1e86e94109f.png)
![image](https://user-images.githubusercontent.com/34165598/72202697-8be87a80-349d-11ea-9043-b6edc448e709.png)

**Comment by serach24** [comment]
一样的问题

**Comment by aircloud** [comment]
发现是有这个问题，原因是目前的 _config.yml 是空，和现在的版本不兼容了，随便加一点内容进去就行..
