### ISSUE TITLE
评论模块加载不出来

### ISSUE THREAD

**Issue by isfox** [aircloud/hexo-theme-aircloud#89]
我用livere做的评论但是加载不出来是什么原因啊
[
![image](https://user-images.githubusercontent.com/31982540/78522000-72d23a00-77fe-11ea-877d-5f27adad5789.png)
](url)

**Comment by aircloud** [comment]
目前好像不维护了

**Comment by anghunk** [comment]
推荐valine，很简单的一个无后端评论系统，唯一的缺点就是无法删除评论，很容易被广告占领
