### ISSUE TITLE
设置favicon.ico

### ISSUE THREAD

**Issue by xingliuhua** [aircloud/hexo-theme-aircloud#9]
如何设置favicon.ico?
how to set favicon.ico?

**Comment by aircloud** [comment]
直接替换掉你的博客项目的  source/img/favicon.ico  （不在模版内替换）
参考[这里](https://github.com/aircloud/hexo-aircloud-blog/blob/master/source/img/favicon.ico)
然后清除缓存后即可生效。
有问题可以进一步交流～
