### ISSUE TITLE
目录上面有颜色

### ISSUE THREAD

**Issue by Salomens** [aircloud/hexo-theme-aircloud#95]
![image](https://user-images.githubusercontent.com/64776123/135192778-fc92b291-e771-46d2-bc95-ad90425dbd8a.png)
这里一直有个蓝色的
![image](https://user-images.githubusercontent.com/64776123/135192847-69a92439-251e-4f58-95bf-5ba7bc20fb05.png)

**Comment by aircloud** [comment]
当前正在浏览的会是蓝色
